using Microsoft.EntityFrameworkCore.Migrations;

namespace Hiroshima.DbData.Migrations
{
    internal static class InitData
    {
        internal static void AddStaticData(MigrationBuilder migrationBuilder)
        {
            var sqlRegions = @"insert into public.""Regions"" (""Id"", ""Name"") VALUES                                
            (150, '{""Ar"": ""أوروبا"", ""Cn"": ""欧洲"", ""En"": ""Europe"", ""Es"": ""Europa"", ""Fr"": ""Europe"", ""Ru"": ""Европа""}' ),
            (2, '{""Ar"": ""أفريقيا"", ""Cn"": ""非洲"", ""En"": ""Africa"", ""Es"": ""África"", ""Fr"": ""Afrique"", ""Ru"": ""Африка""}' ),
            (19, '{""Ar"": ""الأمريكتان"", ""Cn"": ""美洲"", ""En"": ""Americas"", ""Es"": ""América"", ""Fr"": ""Amérique"", ""Ru"": ""Америка""}' ),
            (142, '{""Ar"": ""آسيا"", ""Cn"": ""亚洲"", ""En"": ""Asia"", ""Es"": ""Asia"", ""Fr"": ""Asie"", ""Ru"": ""Азия""}' ),
            (9, '{""Ar"": ""أوقيانوسيا"", ""Cn"": ""大洋洲"", ""En"": ""Oceania"", ""Es"": ""Oceanía"", ""Fr"": ""Océanie"", ""Ru"": ""Океания""}')
            on conflict (""Id"") DO UPDATE SET ""Name"" = excluded.""Name"";";
            migrationBuilder.Sql(sqlRegions);

            var sqlCountries = @"insert into public.""Countries"" (""Code"", ""Name"", ""RegionId"") VALUES
        ('AF', '{""Ar"": ""أفغانستان"", ""Cn"": ""阿富汗"", ""En"": ""Afghanistan"", ""Es"": ""Afganistán"", ""Fr"": ""Afghanistan"", ""Ru"": ""Афганистан""}', 142),
        ('AZ', '{""Ar"": ""أذربيجان"", ""Cn"": ""阿塞拜疆"", ""En"": ""Azerbaijan"", ""Es"": ""Azerbaiyán"", ""Fr"": ""Azerbaïdjan"", ""Ru"": ""Азербайджан""}', 142),
        ('BD', '{""Ar"": ""بنغلاديش"", ""Cn"": ""孟加拉国"", ""En"": ""Bangladesh"", ""Es"": ""Bangladesh"", ""Fr"": ""Bangladesh"", ""Ru"": ""Бангладеш""}', 142),
        ('BI', '{""Ar"": ""بوروندي"", ""Cn"": ""布隆迪"", ""En"": ""Burundi"", ""Es"": ""Burundi"", ""Fr"": ""Burundi"", ""Ru"": ""Бурунди""}', 2),
        ('BN', '{""Ar"": ""بروني دار السلام"", ""Cn"": ""文莱达鲁萨兰国"", ""En"": ""Brunei Darussalam"", ""Es"": ""Brunei Darussalam"", ""Fr"": ""Brunéi Darussalam"", ""Ru"": ""Бруней-Даруссалам""}', 142),
        ('CY', '{""Ar"": ""قبرص"", ""Cn"": ""塞浦路斯"", ""En"": ""Cyprus"", ""Es"": ""Chipre"", ""Fr"": ""Chypre"", ""Ru"": ""Кипр""}', 142),
        ('DM', '{""Ar"": ""دومينيكا"", ""Cn"": ""多米尼克"", ""En"": ""Dominica"", ""Es"": ""Dominica"", ""Fr"": ""Dominique"", ""Ru"": ""Доминика""}', 19),
        ('DO', '{""Ar"": ""الجمهورية الدومينيكية"", ""Cn"": ""多米尼加"", ""En"": ""Dominican Republic"", ""Es"": ""República Dominicana"", ""Fr"": ""République dominicaine"", ""Ru"": ""Доминиканская Республика""}', 19),
        ('GD', '{""Ar"": ""غرينادا"", ""Cn"": ""格林纳达"", ""En"": ""Grenada"", ""Es"": ""Granada"", ""Fr"": ""Grenade"", ""Ru"": ""Гренада""}', 19),
        ('GE', '{""Ar"": ""جورجيا"", ""Cn"": ""格鲁吉亚"", ""En"": ""Georgia"", ""Es"": ""Georgia"", ""Fr"": ""Géorgie"", ""Ru"": ""Грузия""}', 142),
        ('GP', '{""Ar"": ""غوادلوب"", ""Cn"": ""瓜德罗普"", ""En"": ""Guadeloupe"", ""Es"": ""Guadalupe"", ""Fr"": ""Guadeloupe"", ""Ru"": ""Гваделупа""}', 19),
        ('HT', '{""Ar"": ""هايتي"", ""Cn"": ""海地"", ""En"": ""Haiti"", ""Es"": ""Haití"", ""Fr"": ""Haïti"", ""Ru"": ""Гаити""}', 19),
        ('ID', '{""Ar"": ""إندونيسيا"", ""Cn"": ""印度尼西亚"", ""En"": ""Indonesia"", ""Es"": ""Indonesia"", ""Fr"": ""Indonésie"", ""Ru"": ""Индонезия""}', 142),
        ('IL', '{""Ar"": ""إسرائيل"", ""Cn"": ""以色列"", ""En"": ""Israel"", ""Es"": ""Israel"", ""Fr"": ""Israël"", ""Ru"": ""Израиль""}', 142),
        ('IN', '{""Ar"": ""الهند"", ""Cn"": ""印度"", ""En"": ""India"", ""Es"": ""India"", ""Fr"": ""Inde"", ""Ru"": ""Индия""}', 142),
        ('IQ', '{""Ar"": ""العراق"", ""Cn"": ""伊拉克"", ""En"": ""Iraq"", ""Es"": ""Iraq"", ""Fr"": ""Iraq"", ""Ru"": ""Ирак""}', 142),
        ('JM', '{""Ar"": ""جامايكا"", ""Cn"": ""牙买加"", ""En"": ""Jamaica"", ""Es"": ""Jamaica"", ""Fr"": ""Jamaïque"", ""Ru"": ""Ямайка""}', 19),
        ('KG', '{""Ar"": ""قيرغيزستان"", ""Cn"": ""吉尔吉斯斯坦"", ""En"": ""Kyrgyzstan"", ""Es"": ""Kirguistán"", ""Fr"": ""Kirghizistan"", ""Ru"": ""Кыргызстан""}', 142),
        ('KH', '{""Ar"": ""كمبوديا"", ""Cn"": ""柬埔寨"", ""En"": ""Cambodia"", ""Es"": ""Camboya"", ""Fr"": ""Cambodge"", ""Ru"": ""Камбоджа""}', 142),
        ('KN', '{""Ar"": ""سانت كيتس ونيفس"", ""Cn"": ""圣基茨和尼维斯"", ""En"": ""Saint Kitts and Nevis"", ""Es"": ""Saint Kitts y Nevis"", ""Fr"": ""Saint-Kitts-et-Nevis"", ""Ru"": ""Сент-Китс и Невис""}', 19),
        ('KP', '{""Ar"": ""جمهورية كوريا الشعبية الديمقراطية"", ""Cn"": ""朝鲜民主主义人民共和国"", ""En"": ""Democratic People''s Republic of Korea"", ""Es"": ""República Popular Democrática de Corea"", ""Fr"": ""République populaire démocratique de Corée"", ""Ru"": ""Корейская Народно-Демократическая Республика""}', 142),
        ('KY', '{""Ar"": ""جزر كايمان"", ""Cn"": ""开曼群岛"", ""En"": ""Cayman Islands"", ""Es"": ""Islas Caimán"", ""Fr"": ""Îles Caïmanes"", ""Ru"": ""Кайман острова""}', 19),
        ('KZ', '{""Ar"": ""كازاخستان"", ""Cn"": ""哈萨克斯坦"", ""En"": ""Kazakhstan"", ""Es"": ""Kazajstán"", ""Fr"": ""Kazakhstan"", ""Ru"": ""Казахстан""}', 142),
        ('LA', '{""Ar"": ""جمهورية لاو الديمقراطية الشعبية"", ""Cn"": ""老挝人民民主共和国"", ""En"": ""Lao People''s Democratic Republic"", ""Es"": ""República Democrática Popular Lao"", ""Fr"": ""République démocratique populaire lao"", ""Ru"": ""Лаосская Народно-Демократическая Республика""}', 142),
        ('LC', '{""Ar"": ""سانت لوسيا"", ""Cn"": ""圣卢西亚"", ""En"": ""Saint Lucia"", ""Es"": ""Santa Lucía"", ""Fr"": ""Sainte-Lucie"", ""Ru"": ""Сент-Люсия""}', 19),
        ('LK', '{""Ar"": ""سري لانكا"", ""Cn"": ""斯里兰卡"", ""En"": ""Sri Lanka"", ""Es"": ""Sri Lanka"", ""Fr"": ""Sri Lanka"", ""Ru"": ""Шри-Ланка""}', 142),
        ('MM', '{""Ar"": ""ميانمار"", ""Cn"": ""缅甸"", ""En"": ""Myanmar"", ""Es"": ""Myanmar"", ""Fr"": ""Myanmar"", ""Ru"": ""Мьянма""}', 142),
        ('MV', '{""Ar"": ""ملديف"", ""Cn"": ""马尔代夫"", ""En"": ""Maldives"", ""Es"": ""Maldivas"", ""Fr"": ""Maldives"", ""Ru"": ""Мальдивские Острова""}', 142),
        ('MY', '{""Ar"": ""ماليزيا"", ""Cn"": ""马来西亚"", ""En"": ""Malaysia"", ""Es"": ""Malasia"", ""Fr"": ""Malaisie"", ""Ru"": ""Малайзия""}', 142),
        ('NP', '{""Ar"": ""نيبال"", ""Cn"": ""尼泊尔"", ""En"": ""Nepal"", ""Es"": ""Nepal"", ""Fr"": ""Népal"", ""Ru"": ""Непал""}', 142),
        ('PH', '{""Ar"": ""الفلبين"", ""Cn"": ""菲律宾"", ""En"": ""Philippines"", ""Es"": ""Filipinas"", ""Fr"": ""Philippines"", ""Ru"": ""Филиппины""}', 142),
        ('PK', '{""Ar"": ""باكستان"", ""Cn"": ""巴基斯坦"", ""En"": ""Pakistan"", ""Es"": ""Pakistán"", ""Fr"": ""Pakistan"", ""Ru"": ""Пакистан""}', 142),
        ('SG', '{""Ar"": ""سنغافورة"", ""Cn"": ""新加坡"", ""En"": ""Singapore"", ""Es"": ""Singapur"", ""Fr"": ""Singapour"", ""Ru"": ""Сингапур""}', 142),
        ('TH', '{""Ar"": ""تايلند"", ""Cn"": ""泰国"", ""En"": ""Thailand"", ""Es"": ""Tailandia"", ""Fr"": ""Thaïlande"", ""Ru"": ""Таиланд""}', 142),
        ('TJ', '{""Ar"": ""طاجيكستان"", ""Cn"": ""塔吉克斯坦"", ""En"": ""Tajikistan"", ""Es"": ""Tayikistán"", ""Fr"": ""Tadjikistan"", ""Ru"": ""Таджикистан""}', 142),
        ('TL', '{""Ar"": ""تيمور - ليشتي"", ""Cn"": ""东帝汶"", ""En"": ""Timor-Leste"", ""Es"": ""Timor-Leste"", ""Fr"": ""Timor-Leste"", ""Ru"": ""Тимор-Лешти""}', 142),
        ('TM', '{""Ar"": ""تركمانستان"", ""Cn"": ""土库曼斯坦"", ""En"": ""Turkmenistan"", ""Es"": ""Turkmenistán"", ""Fr"": ""Turkménistan"", ""Ru"": ""Туркменистан""}', 142),
        ('UZ', '{""Ar"": ""أوزبكستان"", ""Cn"": ""乌兹别克斯坦"", ""En"": ""Uzbekistan"", ""Es"": ""Uzbekistán"", ""Fr"": ""Ouzbékistan"", ""Ru"": ""Узбекистан""}', 142),
        ('VN', '{""Ar"": ""فييت نام"", ""Cn"": ""越南"", ""En"": ""Viet Nam"", ""Es"": ""Viet Nam"", ""Fr"": ""Viet Nam"", ""Ru"": ""Вьетнам""}', 142),
        ('BH', '{""Ar"": ""البحرين"", ""Cn"": ""巴林"", ""En"": ""Bahrain"", ""Es"": ""Bahrein"", ""Fr"": ""Bahreïn"", ""Ru"": ""Бахрейн""}', 142),
        ('BT', '{""Ar"": ""بوتان"", ""Cn"": ""不丹"", ""En"": ""Bhutan"", ""Es"": ""Bhután"", ""Fr"": ""Bhoutan"", ""Ru"": ""Бутан""}', 142),
        ('CN', '{""Ar"": ""الصين"", ""Cn"": ""中国"", ""En"": ""China"", ""Es"": ""China"", ""Fr"": ""Chine"", ""Ru"": ""Китай""}', 142),
        ('DK', '{""Ar"": ""الدانمرك"", ""Cn"": ""丹麦"", ""En"": ""Denmark"", ""Es"": ""Dinamarca"", ""Fr"": ""Danemark"", ""Ru"": ""Дания""}', 150),
        ('EE', '{""Ar"": ""إستونيا"", ""Cn"": ""爱沙尼亚"", ""En"": ""Estonia"", ""Es"": ""Estonia"", ""Fr"": ""Estonie"", ""Ru"": ""Эстония""}', 150),
        ('FO', '{""Ar"": ""جزر فايرو"", ""Cn"": ""法罗群岛"", ""En"": ""Faroe Islands"", ""Es"": ""Islas Feroe"", ""Fr"": ""Îles Féroé"", ""Ru"": ""Фарерские острова""}', 150),
        ('HK', '{""Ar"": ""الصين، منطقة هونغ كونغ الإدارية الخاصة"", ""Cn"": ""中国香港特别行政区"", ""En"": ""China, Hong Kong Special Administrative Region"", ""Es"": ""China, región administrativa especial de Hong Kong"", ""Fr"": ""Chine, région administrative spéciale de Hong Kong"", ""Ru"": ""Китай, Специальный административный район Гонконг""}', 142),
        ('IE', '{""Ar"": ""آيرلندا"", ""Cn"": ""爱尔兰"", ""En"": ""Ireland"", ""Es"": ""Irlanda"", ""Fr"": ""Irlande"", ""Ru"": ""Ирландия""}', 150),
        ('IM', '{""Ar"": ""جزيرة مان"", ""Cn"": ""马恩岛"", ""En"": ""Isle of Man"", ""Es"": ""Isla de Man"", ""Fr"": ""Île de Man"", ""Ru"": ""Остров Мэн""}', 150),
        ('IS', '{""Ar"": ""آيسلندا"", ""Cn"": ""冰岛"", ""En"": ""Iceland"", ""Es"": ""Islandia"", ""Fr"": ""Islande"", ""Ru"": ""Исландия""}', 150),
        ('JO', '{""Ar"": ""الأردن"", ""Cn"": ""约旦"", ""En"": ""Jordan"", ""Es"": ""Jordania"", ""Fr"": ""Jordanie"", ""Ru"": ""Иордания""}', 142),
        ('JP', '{""Ar"": ""اليابان"", ""Cn"": ""日本"", ""En"": ""Japan"", ""Es"": ""Japón"", ""Fr"": ""Japon"", ""Ru"": ""Япония""}', 142),
        ('KR', '{""Ar"": ""جمهورية كوريا"", ""Cn"": ""大韩民国"", ""En"": ""Republic of Korea"", ""Es"": ""República de Corea"", ""Fr"": ""République de Corée"", ""Ru"": ""Республика Корея""}', 142),
        ('KW', '{""Ar"": ""الكويت"", ""Cn"": ""科威特"", ""En"": ""Kuwait"", ""Es"": ""Kuwait"", ""Fr"": ""Koweït"", ""Ru"": ""Кувейт""}', 142),
        ('LB', '{""Ar"": ""لبنان"", ""Cn"": ""黎巴嫩"", ""En"": ""Lebanon"", ""Es"": ""Líbano"", ""Fr"": ""Liban"", ""Ru"": ""Ливан""}', 142),
        ('LT', '{""Ar"": ""ليتوانيا"", ""Cn"": ""立陶宛"", ""En"": ""Lithuania"", ""Es"": ""Lituania"", ""Fr"": ""Lituanie"", ""Ru"": ""Литва""}', 150),
        ('LV', '{""Ar"": ""لاتفيا"", ""Cn"": ""拉脱维亚"", ""En"": ""Latvia"", ""Es"": ""Letonia"", ""Fr"": ""Lettonie"", ""Ru"": ""Латвия""}', 150),
        ('MF', '{""Ar"": ""سانت مارتن (الجزء الفرنسي)"", ""Cn"": ""圣马丁（法属）"", ""En"": ""Saint Martin (French Part)"", ""Es"": ""San Martín (parte francesa)"", ""Fr"": ""Saint-Martin (partie française)"", ""Ru"": ""Сен-Мартен (французская часть)""}', 19),
        ('MN', '{""Ar"": ""منغوليا"", ""Cn"": ""蒙古"", ""En"": ""Mongolia"", ""Es"": ""Mongolia"", ""Fr"": ""Mongolie"", ""Ru"": ""Монголия""}', 142),
        ('MO', '{""Ar"": ""الصين، منطقة ماكاو الإدارية الخاصة"", ""Cn"": ""中国澳门特别行政区"", ""En"": ""China, Macao Special Administrative Region"", ""Es"": ""China, región administrativa especial de Macao"", ""Fr"": ""Chine, région administrative spéciale de Macao"", ""Ru"": ""Китай, Специальный административный район Макао""}', 142),
        ('MQ', '{""Ar"": ""مارتينيك"", ""Cn"": ""马提尼克"", ""En"": ""Martinique"", ""Es"": ""Martinica"", ""Fr"": ""Martinique"", ""Ru"": ""Мартиника""}', 19),
        ('MS', '{""Ar"": ""مونتسيرات"", ""Cn"": ""蒙特塞拉特"", ""En"": ""Montserrat"", ""Es"": ""Montserrat"", ""Fr"": ""Montserrat"", ""Ru"": ""Монтсеррат""}', 19),
        ('NO', '{""Ar"": ""النرويج"", ""Cn"": ""挪威"", ""En"": ""Norway"", ""Es"": ""Noruega"", ""Fr"": ""Norvège"", ""Ru"": ""Норвегия""}', 150),
        ('PR', '{""Ar"": ""بورتوريكو"", ""Cn"": ""波多黎各"", ""En"": ""Puerto Rico"", ""Es"": ""Puerto Rico"", ""Fr"": ""Porto Rico"", ""Ru"": ""Пуэрто-Рико""}', 19),
        ('RO', '{""Ar"": ""رومانيا"", ""Cn"": ""罗马尼亚"", ""En"": ""Romania"", ""Es"": ""Rumania"", ""Fr"": ""Roumanie"", ""Ru"": ""Румыния""}', 150),
        ('RU', '{""Ar"": ""الاتحاد الروسي"", ""Cn"": ""俄罗斯联邦"", ""En"": ""Russian Federation"", ""Es"": ""Federación de Rusia"", ""Fr"": ""Fédération de Russie"", ""Ru"": ""Российская Федерация""}', 150),
        ('SK', '{""Ar"": ""سلوفاكيا"", ""Cn"": ""斯洛伐克"", ""En"": ""Slovakia"", ""Es"": ""Eslovaquia"", ""Fr"": ""Slovaquie"", ""Ru"": ""Словакия""}', 150),
        ('SX', '{""Ar"": ""سانت مارتن (الجزء الهولندي)"", ""Cn"": ""圣马丁（荷属）"", ""En"": ""Sint Maarten (Dutch part)"", ""Es"": ""San Martín (parte Holandesa)"", ""Fr"": ""Saint-Martin (partie néerlandaise)"", ""Ru"": ""Синт-Мартен (нидерландская часть)""}', 19),
        ('TC', '{""Ar"": ""جزر تركس وكايكوس"", ""Cn"": ""特克斯和凯科斯群岛"", ""En"": ""Turks and Caicos Islands"", ""Es"": ""Islas Turcas y Caicos"", ""Fr"": ""Îles Turques-et-Caïques"", ""Ru"": ""Острова Теркс и Кайкос""}', 19),
        ('TT', '{""Ar"": ""ترينيداد وتوباغو"", ""Cn"": ""特立尼达和多巴哥"", ""En"": ""Trinidad and Tobago"", ""Es"": ""Trinidad y Tabago"", ""Fr"": ""Trinité-et-Tobago"", ""Ru"": ""Тринидад и Тобаго""}', 19),
        ('UA', '{""Ar"": ""أوكرانيا"", ""Cn"": ""乌克兰"", ""En"": ""Ukraine"", ""Es"": ""Ucrania"", ""Fr"": ""Ukraine"", ""Ru"": ""Украина""}', 150),
        ('VC', '{""Ar"": ""سانت فنسنت وجزر غرينادين"", ""Cn"": ""圣文森特和格林纳丁斯"", ""En"": ""Saint Vincent and the Grenadines"", ""Es"": ""San Vicente y las Granadinas"", ""Fr"": ""Saint-Vincent-et-les Grenadines"", ""Ru"": ""Сент-Винсент и Гренадины""}', 19),
        ('VG', '{""Ar"": ""جزر فرجن البريطانية"", ""Cn"": ""英属维尔京群岛"", ""En"": ""British Virgin Islands"", ""Es"": ""Islas Vírgenes Británicas"", ""Fr"": ""Îles Vierges britanniques"", ""Ru"": ""Британские Виргинские острова""}', 19),
        ('VI', '{""Ar"": ""جزر فرجن التابعة للولايات المتحدة"", ""Cn"": ""美属维尔京群岛"", ""En"": ""United States Virgin Islands"", ""Es"": ""Islas Vírgenes de los Estados Unidos"", ""Fr"": ""Îles Vierges américaines"", ""Ru"": ""Виргинские острова Соединенных Штатов""}', 19),
        ('AD', '{""Ar"": ""أندورا"", ""Cn"": ""安道尔"", ""En"": ""Andorra"", ""Es"": ""Andorra"", ""Fr"": ""Andorre"", ""Ru"": ""Андорра""}', 150),
        ('AT', '{""Ar"": ""النمسا"", ""Cn"": ""奥地利"", ""En"": ""Austria"", ""Es"": ""Austria"", ""Fr"": ""Autriche"", ""Ru"": ""Австрия""}', 150),
        ('AX', '{""Ar"": ""جزر ألاند"", ""Cn"": ""奥兰群岛"", ""En"": ""Åland Islands"", ""Es"": ""Islas Åland"", ""Fr"": ""Îles d’Åland"", ""Ru"": ""Аландских островов""}', 150),
        ('BA', '{""Ar"": ""البوسنة والهرسك"", ""Cn"": ""波斯尼亚和黑塞哥维那"", ""En"": ""Bosnia and Herzegovina"", ""Es"": ""Bosnia y Herzegovina"", ""Fr"": ""Bosnie-Herzégovine"", ""Ru"": ""Босния и Герцеговина""}', 150),
        ('BE', '{""Ar"": ""بلجيكا"", ""Cn"": ""比利时"", ""En"": ""Belgium"", ""Es"": ""Bélgica"", ""Fr"": ""Belgique"", ""Ru"": ""Бельгия""}', 150),
        ('BG', '{""Ar"": ""بلغاريا"", ""Cn"": ""保加利亚"", ""En"": ""Bulgaria"", ""Es"": ""Bulgaria"", ""Fr"": ""Bulgarie"", ""Ru"": ""Болгария""}', 150),
        ('BY', '{""Ar"": ""بيلاروس"", ""Cn"": ""白俄罗斯"", ""En"": ""Belarus"", ""Es"": ""Belarús"", ""Fr"": ""Bélarus"", ""Ru"": ""Беларусь""}', 150),
        ('CH', '{""Ar"": ""سويسرا"", ""Cn"": ""瑞士"", ""En"": ""Switzerland"", ""Es"": ""Suiza"", ""Fr"": ""Suisse"", ""Ru"": ""Швейцария""}', 150),
        ('CU', '{""Ar"": ""كوبا"", ""Cn"": ""古巴"", ""En"": ""Cuba"", ""Es"": ""Cuba"", ""Fr"": ""Cuba"", ""Ru"": ""Куба""}', 19),
        ('CZ', '{""Ar"": ""تشيكيا"", ""Cn"": ""捷克"", ""En"": ""Czechia"", ""Es"": ""Chequia"", ""Fr"": ""Tchéquie"", ""Ru"": ""Чехия""}', 150),
        ('DE', '{""Ar"": ""ألمانيا"", ""Cn"": ""德国"", ""En"": ""Germany"", ""Es"": ""Alemania"", ""Fr"": ""Allemagne"", ""Ru"": ""Германия""}', 150),
        ('ES', '{""Ar"": ""إسبانيا"", ""Cn"": ""西班牙"", ""En"": ""Spain"", ""Es"": ""España"", ""Fr"": ""Espagne"", ""Ru"": ""Испания""}', 150),
        ('FR', '{""Ar"": ""فرنسا"", ""Cn"": ""法国"", ""En"": ""France"", ""Es"": ""Francia"", ""Fr"": ""France"", ""Ru"": ""Франция""}', 150),
        ('GG', '{""Ar"": ""غيرنسي"", ""Cn"": ""格恩西"", ""En"": ""Guernsey"", ""Es"": ""Guernsey"", ""Fr"": ""Guernesey"", ""Ru"": ""Гернси""}', 150),
        ('GI', '{""Ar"": ""جبل طارق"", ""Cn"": ""直布罗陀"", ""En"": ""Gibraltar"", ""Es"": ""Gibraltar"", ""Fr"": ""Gibraltar"", ""Ru"": ""Гибралтар""}', 150),
        ('GR', '{""Ar"": ""اليونان"", ""Cn"": ""希腊"", ""En"": ""Greece"", ""Es"": ""Grecia"", ""Fr"": ""Grèce"", ""Ru"": ""Греция""}', 150),
        ('HR', '{""Ar"": ""كرواتيا"", ""Cn"": ""克罗地亚"", ""En"": ""Croatia"", ""Es"": ""Croacia"", ""Fr"": ""Croatie"", ""Ru"": ""Хорватия""}', 150),
        ('HU', '{""Ar"": ""هنغاريا"", ""Cn"": ""匈牙利"", ""En"": ""Hungary"", ""Es"": ""Hungría"", ""Fr"": ""Hongrie"", ""Ru"": ""Венгрия""}', 150),
        ('IT', '{""Ar"": ""إيطاليا"", ""Cn"": ""意大利"", ""En"": ""Italy"", ""Es"": ""Italia"", ""Fr"": ""Italie"", ""Ru"": ""Италия""}', 150),
        ('JE', '{""Ar"": ""جيرسي"", ""Cn"": ""泽西"", ""En"": ""Jersey"", ""Es"": ""Jersey"", ""Fr"": ""Jersey"", ""Ru"": ""Джерси""}', 150),
        ('LI', '{""Ar"": ""ليختنشتاين"", ""Cn"": ""列支敦士登"", ""En"": ""Liechtenstein"", ""Es"": ""Liechtenstein"", ""Fr"": ""Liechtenstein"", ""Ru"": ""Лихтенштейн""}', 150),
        ('LU', '{""Ar"": ""لكسمبرغ"", ""Cn"": ""卢森堡"", ""En"": ""Luxembourg"", ""Es"": ""Luxemburgo"", ""Fr"": ""Luxembourg"", ""Ru"": ""Люксембург""}', 150),
        ('MC', '{""Ar"": ""موناكو"", ""Cn"": ""摩纳哥"", ""En"": ""Monaco"", ""Es"": ""Mónaco"", ""Fr"": ""Monaco"", ""Ru"": ""Монако""}', 150),
        ('ME', '{""Ar"": ""الجبل الأسود"", ""Cn"": ""黑山"", ""En"": ""Montenegro"", ""Es"": ""Montenegro"", ""Fr"": ""Monténégro"", ""Ru"": ""Черногория""}', 150),
        ('MK', '{""Ar"": ""مقدونيا الشمالية"", ""Cn"": ""北马其顿"", ""En"": ""North Macedonia"", ""Es"": ""Macedonia del Norte"", ""Fr"": ""Macédoine du Nord"", ""Ru"": ""Северная Македония""}', 150),
        ('MT', '{""Ar"": ""مالطة"", ""Cn"": ""马耳他"", ""En"": ""Malta"", ""Es"": ""Malta"", ""Fr"": ""Malte"", ""Ru"": ""Мальта""}', 150),
        ('NL', '{""Ar"": ""هولندا"", ""Cn"": ""荷兰"", ""En"": ""Netherlands"", ""Es"": ""Países Bajos"", ""Fr"": ""Pays-Bas"", ""Ru"": ""Нидерланды""}', 150),
        ('OM', '{""Ar"": ""عمان"", ""Cn"": ""阿曼"", ""En"": ""Oman"", ""Es"": ""Omán"", ""Fr"": ""Oman"", ""Ru"": ""Оман""}', 142),
        ('PL', '{""Ar"": ""بولندا"", ""Cn"": ""波兰"", ""En"": ""Poland"", ""Es"": ""Polonia"", ""Fr"": ""Pologne"", ""Ru"": ""Польша""}', 150),
        ('PS', '{""Ar"": ""دولة فلسطين"", ""Cn"": ""巴勒斯坦国"", ""En"": ""State of Palestine"", ""Es"": ""Estado de Palestina"", ""Fr"": ""État de Palestine"", ""Ru"": ""Государство Палестина""}', 142),
        ('PT', '{""Ar"": ""البرتغال"", ""Cn"": ""葡萄牙"", ""En"": ""Portugal"", ""Es"": ""Portugal"", ""Fr"": ""Portugal"", ""Ru"": ""Португалия""}', 150),
        ('QA', '{""Ar"": ""قطر"", ""Cn"": ""卡塔尔"", ""En"": ""Qatar"", ""Es"": ""Qatar"", ""Fr"": ""Qatar"", ""Ru"": ""Катар""}', 142),
        ('RS', '{""Ar"": ""صربيا"", ""Cn"": ""塞尔维亚"", ""En"": ""Serbia"", ""Es"": ""Serbia"", ""Fr"": ""Serbie"", ""Ru"": ""Сербия""}', 150),
        ('SA', '{""Ar"": ""المملكة العربية السعودية"", ""Cn"": ""沙特阿拉伯"", ""En"": ""Saudi Arabia"", ""Es"": ""Arabia Saudita"", ""Fr"": ""Arabie saoudite"", ""Ru"": ""Саудовская Аравия""}', 142),
        ('SE', '{""Ar"": ""السويد"", ""Cn"": ""瑞典"", ""En"": ""Sweden"", ""Es"": ""Suecia"", ""Fr"": ""Suède"", ""Ru"": ""Швеция""}', 150),
        ('SI', '{""Ar"": ""سلوفينيا"", ""Cn"": ""斯洛文尼亚"", ""En"": ""Slovenia"", ""Es"": ""Eslovenia"", ""Fr"": ""Slovénie"", ""Ru"": ""Словения""}', 150),
        ('SJ', '{""Ar"": ""جزيرتي سفالبارد وجان مايِن"", ""Cn"": ""斯瓦尔巴群岛和扬马延岛"", ""En"": ""Svalbard and Jan Mayen Islands"", ""Es"": ""Islas Svalbard y Jan Mayen"", ""Fr"": ""Îles Svalbard-et-Jan Mayen"", ""Ru"": ""Острова Свальбард и Ян-Майен""}', 150),
        ('SM', '{""Ar"": ""سان مارينو"", ""Cn"": ""圣马力诺"", ""En"": ""San Marino"", ""Es"": ""San Marino"", ""Fr"": ""Saint-Marin"", ""Ru"": ""Сан-Марино""}', 150),
        ('SY', '{""Ar"": ""الجمهورية العربية السورية"", ""Cn"": ""阿拉伯叙利亚共和国"", ""En"": ""Syrian Arab Republic"", ""Es"": ""República Árabe Siria"", ""Fr"": ""République arabe syrienne"", ""Ru"": ""Сирийская Арабская Республика""}', 142),
        ('TR', '{""Ar"": ""تركيا"", ""Cn"": ""土耳其"", ""En"": ""Turkey"", ""Es"": ""Turquía"", ""Fr"": ""Turquie"", ""Ru"": ""Турция""}', 142),
        ('VA', '{""Ar"": ""الكرسي الرسولي"", ""Cn"": ""教廷"", ""En"": ""Holy See"", ""Es"": ""Santa Sede"", ""Fr"": ""Saint-Siège"", ""Ru"": ""Святой Престол""}', 150),
        ('YE', '{""Ar"": ""اليمن"", ""Cn"": ""也门"", ""En"": ""Yemen"", ""Es"": ""Yemen"", ""Fr"": ""Yémen"", ""Ru"": ""Йемен""}', 142),
        ('BJ', '{""Ar"": ""بنن"", ""Cn"": ""贝宁"", ""En"": ""Benin"", ""Es"": ""Benin"", ""Fr"": ""Bénin"", ""Ru"": ""Бенин""}', 2),
        ('BS', '{""Ar"": ""جزر البهاما"", ""Cn"": ""巴哈马"", ""En"": ""Bahamas"", ""Es"": ""Bahamas"", ""Fr"": ""Bahamas"", ""Ru"": ""Багамские Острова""}', 19),
        ('BW', '{""Ar"": ""بوتسوانا"", ""Cn"": ""博茨瓦纳"", ""En"": ""Botswana"", ""Es"": ""Botswana"", ""Fr"": ""Botswana"", ""Ru"": ""Ботсвана""}', 2),
        ('CF', '{""Ar"": ""جمهورية أفريقيا الوسطى"", ""Cn"": ""中非共和国"", ""En"": ""Central African Republic"", ""Es"": ""República Centroafricana"", ""Fr"": ""République centrafricaine"", ""Ru"": ""Центральноафриканская Республика""}', 2),
        ('CG', '{""Ar"": ""الكونغو"", ""Cn"": ""刚果"", ""En"": ""Congo"", ""Es"": ""Congo"", ""Fr"": ""Congo"", ""Ru"": ""Конго""}', 2),
        ('CI', '{""Ar"": ""كوت ديفوار"", ""Cn"": ""科特迪瓦"", ""En"": ""Côte d’Ivoire"", ""Es"": ""Côte d’Ivoire"", ""Fr"": ""Côte d’Ivoire"", ""Ru"": ""Кот-д''Ивуар""}', 2),
        ('CM', '{""Ar"": ""الكاميرون"", ""Cn"": ""喀麦隆"", ""En"": ""Cameroon"", ""Es"": ""Camerún"", ""Fr"": ""Cameroun"", ""Ru"": ""Камерун""}', 2),
        ('CV', '{""Ar"": ""كابو فيردي"", ""Cn"": ""佛得角"", ""En"": ""Cabo Verde"", ""Es"": ""Cabo Verde"", ""Fr"": ""Cabo Verde"", ""Ru"": ""Кабо-Верде""}', 2),
        ('CW', '{""Ar"": ""كوراساو"", ""Cn"": ""库拉索"", ""En"": ""Curaçao"", ""Es"": ""Curazao"", ""Fr"": ""Curaçao"", ""Ru"": ""Кюрасао""}', 19),
        ('DZ', '{""Ar"": ""الجزائر"", ""Cn"": ""阿尔及利亚"", ""En"": ""Algeria"", ""Es"": ""Argelia"", ""Fr"": ""Algérie"", ""Ru"": ""Алжир""}', 2),
        ('EG', '{""Ar"": ""مصر"", ""Cn"": ""埃及"", ""En"": ""Egypt"", ""Es"": ""Egipto"", ""Fr"": ""Égypte"", ""Ru"": ""Египет""}', 2),
        ('EH', '{""Ar"": ""الصحراء الغربية"", ""Cn"": ""西撒哈拉"", ""En"": ""Western Sahara"", ""Es"": ""Sáhara Occidental"", ""Fr"": ""Sahara occidental"", ""Ru"": ""Западная Сахара""}', 2),
        ('GA', '{""Ar"": ""غابون"", ""Cn"": ""加蓬"", ""En"": ""Gabon"", ""Es"": ""Gabón"", ""Fr"": ""Gabon"", ""Ru"": ""Габон""}', 2),
        ('GH', '{""Ar"": ""غانا"", ""Cn"": ""加纳"", ""En"": ""Ghana"", ""Es"": ""Ghana"", ""Fr"": ""Ghana"", ""Ru"": ""Гана""}', 2),
        ('GM', '{""Ar"": ""غامبيا"", ""Cn"": ""冈比亚"", ""En"": ""Gambia"", ""Es"": ""Gambia"", ""Fr"": ""Gambie"", ""Ru"": ""Гамбия""}', 2),
        ('GN', '{""Ar"": ""غينيا"", ""Cn"": ""几内亚"", ""En"": ""Guinea"", ""Es"": ""Guinea"", ""Fr"": ""Guinée"", ""Ru"": ""Гвинея""}', 2),
        ('GQ', '{""Ar"": ""غينيا الاستوائية"", ""Cn"": ""赤道几内亚"", ""En"": ""Equatorial Guinea"", ""Es"": ""Guinea Ecuatorial"", ""Fr"": ""Guinée équatoriale"", ""Ru"": ""Экваториальная Гвинея""}', 2),
        ('GW', '{""Ar"": ""غينيا - بيساو"", ""Cn"": ""几内亚比绍"", ""En"": ""Guinea-Bissau"", ""Es"": ""Guinea-Bissau"", ""Fr"": ""Guinée-Bissau"", ""Ru"": ""Гвинея-Бисау""}', 2),
        ('LR', '{""Ar"": ""ليبريا"", ""Cn"": ""利比里亚"", ""En"": ""Liberia"", ""Es"": ""Liberia"", ""Fr"": ""Libéria"", ""Ru"": ""Либерия""}', 2),
        ('LS', '{""Ar"": ""ليسوتو"", ""Cn"": ""莱索托"", ""En"": ""Lesotho"", ""Es"": ""Lesotho"", ""Fr"": ""Lesotho"", ""Ru"": ""Лесото""}', 2),
        ('LY', '{""Ar"": ""ليبيا"", ""Cn"": ""利比亚"", ""En"": ""Libya"", ""Es"": ""Libia"", ""Fr"": ""Libye"", ""Ru"": ""Ливия""}', 2),
        ('MA', '{""Ar"": ""المغرب"", ""Cn"": ""摩洛哥"", ""En"": ""Morocco"", ""Es"": ""Marruecos"", ""Fr"": ""Maroc"", ""Ru"": ""Марокко""}', 2),
        ('ML', '{""Ar"": ""مالي"", ""Cn"": ""马里"", ""En"": ""Mali"", ""Es"": ""Malí"", ""Fr"": ""Mali"", ""Ru"": ""Мали""}', 2),
        ('MR', '{""Ar"": ""موريتانيا"", ""Cn"": ""毛里塔尼亚"", ""En"": ""Mauritania"", ""Es"": ""Mauritania"", ""Fr"": ""Mauritanie"", ""Ru"": ""Мавритания""}', 2),
        ('MW', '{""Ar"": ""ملاوي"", ""Cn"": ""马拉维"", ""En"": ""Malawi"", ""Es"": ""Malawi"", ""Fr"": ""Malawi"", ""Ru"": ""Малави""}', 2),
        ('NA', '{""Ar"": ""ناميبيا"", ""Cn"": ""纳米比亚"", ""En"": ""Namibia"", ""Es"": ""Namibia"", ""Fr"": ""Namibie"", ""Ru"": ""Намибия""}', 2),
        ('NE', '{""Ar"": ""النيجر"", ""Cn"": ""尼日尔"", ""En"": ""Niger"", ""Es"": ""Níger"", ""Fr"": ""Niger"", ""Ru"": ""Нигер""}', 2),
        ('RE', '{""Ar"": ""ريونيون"", ""Cn"": ""留尼汪"", ""En"": ""Réunion"", ""Es"": ""Reunión"", ""Fr"": ""Réunion"", ""Ru"": ""Реюньон""}', 2),
        ('RW', '{""Ar"": ""رواندا"", ""Cn"": ""卢旺达"", ""En"": ""Rwanda"", ""Es"": ""Rwanda"", ""Fr"": ""Rwanda"", ""Ru"": ""Руанда""}', 2),
        ('SC', '{""Ar"": ""سيشيل"", ""Cn"": ""塞舌尔"", ""En"": ""Seychelles"", ""Es"": ""Seychelles"", ""Fr"": ""Seychelles"", ""Ru"": ""Сейшельские Острова""}', 2),
        ('SD', '{""Ar"": ""السودان"", ""Cn"": ""苏丹"", ""En"": ""Sudan"", ""Es"": ""Sudán"", ""Fr"": ""Soudan"", ""Ru"": ""Судан""}', 2),
        ('SO', '{""Ar"": ""الصومال"", ""Cn"": ""索马里"", ""En"": ""Somalia"", ""Es"": ""Somalia"", ""Fr"": ""Somalie"", ""Ru"": ""Сомали""}', 2),
        ('SS', '{""Ar"": ""جنوب السودان"", ""Cn"": ""南苏丹"", ""En"": ""South Sudan"", ""Es"": ""Sudán del Sur"", ""Fr"": ""Soudan du Sud"", ""Ru"": ""Южный Судан""}', 2),
        ('ST', '{""Ar"": ""سان تومي وبرينسيبي"", ""Cn"": ""圣多美和普林西比"", ""En"": ""Sao Tome and Principe"", ""Es"": ""Santo Tomé y Príncipe"", ""Fr"": ""Sao Tomé-et-Principe"", ""Ru"": ""Сан-Томе и Принсипи""}', 2),
        ('SZ', '{""Ar"": ""إسواتيني"", ""Cn"": ""斯威士兰"", ""En"": ""Eswatini"", ""Es"": ""Eswatini"", ""Fr"": ""Eswatini"", ""Ru"": ""Эсватини""}', 2),
        ('TD', '{""Ar"": ""تشاد"", ""Cn"": ""乍得"", ""En"": ""Chad"", ""Es"": ""Chad"", ""Fr"": ""Tchad"", ""Ru"": ""Чад""}', 2),
        ('TN', '{""Ar"": ""تونس"", ""Cn"": ""突尼斯"", ""En"": ""Tunisia"", ""Es"": ""Túnez"", ""Fr"": ""Tunisie"", ""Ru"": ""Тунис""}', 2),
        ('TZ', '{""Ar"": ""جمهورية تنزانيا المتحدة"", ""Cn"": ""坦桑尼亚联合共和国"", ""En"": ""United Republic of Tanzania"", ""Es"": ""República Unida de Tanzanía"", ""Fr"": ""République-Unie de Tanzanie"", ""Ru"": ""Объединенная Республика Танзания""}', 2),
        ('UG', '{""Ar"": ""أوغندا"", ""Cn"": ""乌干达"", ""En"": ""Uganda"", ""Es"": ""Uganda"", ""Fr"": ""Ouganda"", ""Ru"": ""Уганда""}', 2),
        ('YT', '{""Ar"": ""مايوت"", ""Cn"": ""马约特"", ""En"": ""Mayotte"", ""Es"": ""Mayotte"", ""Fr"": ""Mayotte"", ""Ru"": ""Остров Майотта""}', 2),
        ('ZA', '{""Ar"": ""جنوب أفريقيا"", ""Cn"": ""南非"", ""En"": ""South Africa"", ""Es"": ""Sudáfrica"", ""Fr"": ""Afrique du Sud"", ""Ru"": ""Южная Африка""}', 2),
        ('ZM', '{""Ar"": ""زامبيا"", ""Cn"": ""赞比亚"", ""En"": ""Zambia"", ""Es"": ""Zambia"", ""Fr"": ""Zambie"", ""Ru"": ""Замбия""}', 2),
        ('ZW', '{""Ar"": ""زمبابوي"", ""Cn"": ""津巴布韦"", ""En"": ""Zimbabwe"", ""Es"": ""Zimbabwe"", ""Fr"": ""Zimbabwe"", ""Ru"": ""Зимбабве""}', 2),
        ('AS', '{""Ar"": ""ساموا الأمريكية"", ""Cn"": ""美属萨摩亚"", ""En"": ""American Samoa"", ""Es"": ""Samoa Americana"", ""Fr"": ""Samoa américaines"", ""Ru"": ""Американское Самоа""}', 9),
        ('AU', '{""Ar"": ""أستراليا"", ""Cn"": ""澳大利亚"", ""En"": ""Australia"", ""Es"": ""Australia"", ""Fr"": ""Australie"", ""Ru"": ""Австралия""}', 9),
        ('BF', '{""Ar"": ""بوركينا فاسو"", ""Cn"": ""布基纳法索"", ""En"": ""Burkina Faso"", ""Es"": ""Burkina Faso"", ""Fr"": ""Burkina Faso"", ""Ru"": ""Буркина-Фасо""}', 2),
        ('BL', '{""Ar"": ""سان بارتليمي"", ""Cn"": ""圣巴泰勒米"", ""En"": ""Saint Barthélemy"", ""Es"": ""San Barthélemy"", ""Fr"": ""Saint-Barthélemy"", ""Ru"": ""Сен-Бартелеми""}', 19),
        ('BZ', '{""Ar"": ""بليز"", ""Cn"": ""伯利兹"", ""En"": ""Belize"", ""Es"": ""Belice"", ""Fr"": ""Belize"", ""Ru"": ""Белиз""}', 19),
        ('CR', '{""Ar"": ""كوستاريكا"", ""Cn"": ""哥斯达黎加"", ""En"": ""Costa Rica"", ""Es"": ""Costa Rica"", ""Fr"": ""Costa Rica"", ""Ru"": ""Коста-Рика""}', 19),
        ('CX', '{""Ar"": ""جزيرة عيد الميلاد"", ""Cn"": ""圣诞岛"", ""En"": ""Christmas Island"", ""Es"": ""Isla Christmas"", ""Fr"": ""Île Christmas"", ""Ru"": ""остров Рождества""}', 9),
        ('DJ', '{""Ar"": ""جيبوتي"", ""Cn"": ""吉布提"", ""En"": ""Djibouti"", ""Es"": ""Djibouti"", ""Fr"": ""Djibouti"", ""Ru"": ""Джибути""}', 2),
        ('ER', '{""Ar"": ""إريتريا"", ""Cn"": ""厄立特里亚"", ""En"": ""Eritrea"", ""Es"": ""Eritrea"", ""Fr"": ""Érythrée"", ""Ru"": ""Эритрея""}', 2),
        ('ET', '{""Ar"": ""إثيوبيا"", ""Cn"": ""埃塞俄比亚"", ""En"": ""Ethiopia"", ""Es"": ""Etiopía"", ""Fr"": ""Éthiopie"", ""Ru"": ""Эфиопия""}', 2),
        ('FK', '{""Ar"": ""جزر فوكلاند (مالفيناس)"", ""Cn"": ""福克兰群岛（马尔维纳斯）"", ""En"": ""Falkland Islands (Malvinas)"", ""Es"": ""Islas Malvinas (Falkland)"", ""Fr"": ""Îles Falkland (Malvinas)"", ""Ru"": ""Фолклендские (Мальвинские) острова""}', 19),
        ('GF', '{""Ar"": ""غيانا الفرنسية"", ""Cn"": ""法属圭亚那"", ""En"": ""French Guiana"", ""Es"": ""Guayana Francesa"", ""Fr"": ""Guyane française"", ""Ru"": ""Французская Гвиана""}', 19),
        ('GS', '{""Ar"": ""جورجيا الجنوبية وجزر ساندويتش الجنوبية"", ""Cn"": ""南乔治亚岛和南桑德韦奇岛"", ""En"": ""South Georgia and the South Sandwich Islands"", ""Es"": ""Georgia del Sur y las Islas Sandwich del Sur"", ""Fr"": ""Géorgie du Sud-et-les Îles Sandwich du Sud"", ""Ru"": ""Южная Джорджия и Южные Сандвичевы острова""}', 19),
        ('GT', '{""Ar"": ""غواتيمالا"", ""Cn"": ""危地马拉"", ""En"": ""Guatemala"", ""Es"": ""Guatemala"", ""Fr"": ""Guatemala"", ""Ru"": ""Гватемала""}', 19),
        ('GY', '{""Ar"": ""غيانا"", ""Cn"": ""圭亚那"", ""En"": ""Guyana"", ""Es"": ""Guyana"", ""Fr"": ""Guyana"", ""Ru"": ""Гайана""}', 19),
        ('HN', '{""Ar"": ""هندوراس"", ""Cn"": ""洪都拉斯"", ""En"": ""Honduras"", ""Es"": ""Honduras"", ""Fr"": ""Honduras"", ""Ru"": ""Гондурас""}', 19),
        ('IO', '{""Ar"": ""المحيط الهندي الإقليم البريطاني في"", ""Cn"": ""英属印度洋领土"", ""En"": ""British Indian Ocean Territory"", ""Es"": ""Territorio Británico del Océano Índico"", ""Fr"": ""Territoire britannique de l''océan Indien"", ""Ru"": ""Британская территория в Индийском океане""}', 2),
        ('KE', '{""Ar"": ""كينيا"", ""Cn"": ""肯尼亚"", ""En"": ""Kenya"", ""Es"": ""Kenya"", ""Fr"": ""Kenya"", ""Ru"": ""Кения""}', 2),
        ('KM', '{""Ar"": ""جزر القمر"", ""Cn"": ""科摩罗"", ""En"": ""Comoros"", ""Es"": ""Comoras"", ""Fr"": ""Comores"", ""Ru"": ""Коморские Острова""}', 2),
        ('MG', '{""Ar"": ""مدغشقر"", ""Cn"": ""马达加斯加"", ""En"": ""Madagascar"", ""Es"": ""Madagascar"", ""Fr"": ""Madagascar"", ""Ru"": ""Мадагаскар""}', 2),
        ('MU', '{""Ar"": ""موريشيوس"", ""Cn"": ""毛里求斯"", ""En"": ""Mauritius"", ""Es"": ""Mauricio"", ""Fr"": ""Maurice"", ""Ru"": ""Маврикий""}', 2),
        ('MX', '{""Ar"": ""المكسيك"", ""Cn"": ""墨西哥"", ""En"": ""Mexico"", ""Es"": ""México"", ""Fr"": ""Mexique"", ""Ru"": ""Мексика""}', 19),
        ('MZ', '{""Ar"": ""موزامبيق"", ""Cn"": ""莫桑比克"", ""En"": ""Mozambique"", ""Es"": ""Mozambique"", ""Fr"": ""Mozambique"", ""Ru"": ""Мозамбик""}', 2),
        ('NG', '{""Ar"": ""نيجيريا"", ""Cn"": ""尼日利亚"", ""En"": ""Nigeria"", ""Es"": ""Nigeria"", ""Fr"": ""Nigéria"", ""Ru"": ""Нигерия""}', 2),
        ('NI', '{""Ar"": ""نيكاراغوا"", ""Cn"": ""尼加拉瓜"", ""En"": ""Nicaragua"", ""Es"": ""Nicaragua"", ""Fr"": ""Nicaragua"", ""Ru"": ""Никарагуа""}', 19),
        ('PA', '{""Ar"": ""بنما"", ""Cn"": ""巴拿马"", ""En"": ""Panama"", ""Es"": ""Panamá"", ""Fr"": ""Panama"", ""Ru"": ""Панама""}', 19),
        ('PE', '{""Ar"": ""بيرو"", ""Cn"": ""秘鲁"", ""En"": ""Peru"", ""Es"": ""Perú"", ""Fr"": ""Pérou"", ""Ru"": ""Перу""}', 19),
        ('PY', '{""Ar"": ""باراغواي"", ""Cn"": ""巴拉圭"", ""En"": ""Paraguay"", ""Es"": ""Paraguay"", ""Fr"": ""Paraguay"", ""Ru"": ""Парагвай""}', 19),
        ('SH', '{""Ar"": ""سانت هيلانة"", ""Cn"": ""圣赫勒拿"", ""En"": ""Saint Helena"", ""Es"": ""Santa Elena"", ""Fr"": ""Sainte-Hélène"", ""Ru"": ""Остров Святой Елены""}', 2),
        ('SL', '{""Ar"": ""سيراليون"", ""Cn"": ""塞拉利昂"", ""En"": ""Sierra Leone"", ""Es"": ""Sierra Leona"", ""Fr"": ""Sierra Leone"", ""Ru"": ""Сьерра-Леоне""}', 2),
        ('SN', '{""Ar"": ""السنغال"", ""Cn"": ""塞内加尔"", ""En"": ""Senegal"", ""Es"": ""Senegal"", ""Fr"": ""Sénégal"", ""Ru"": ""Сенегал""}', 2),
        ('SR', '{""Ar"": ""سورينام"", ""Cn"": ""苏里南"", ""En"": ""Suriname"", ""Es"": ""Suriname"", ""Fr"": ""Suriname"", ""Ru"": ""Суринам""}', 19),
        ('SV', '{""Ar"": ""السلفادور"", ""Cn"": ""萨尔瓦多"", ""En"": ""El Salvador"", ""Es"": ""El Salvador"", ""Fr"": ""El Salvador"", ""Ru"": ""Сальвадор""}', 19),
        ('TF', '{""Ar"": ""الأراضي الفرنسية الجنوبية الجنوبية"", ""Cn"": ""法属南方领地"", ""En"": ""French Southern Territories"", ""Es"": ""Territorio de las Tierras Australes Francesas"", ""Fr"": ""Terres australes françaises"", ""Ru"": ""Южные земли (французская заморская территория)""}', 2),
        ('TG', '{""Ar"": ""توغو"", ""Cn"": ""多哥"", ""En"": ""Togo"", ""Es"": ""Togo"", ""Fr"": ""Togo"", ""Ru"": ""Того""}', 2),
        ('UY', '{""Ar"": ""أوروغواي"", ""Cn"": ""乌拉圭"", ""En"": ""Uruguay"", ""Es"": ""Uruguay"", ""Fr"": ""Uruguay"", ""Ru"": ""Уругвай""}', 19),
        ('VE', '{""Ar"": ""فنزويلا (جمهورية - البوليفارية)"", ""Cn"": ""委内瑞拉玻利瓦尔共和国"", ""En"": ""Venezuela (Bolivarian Republic of)"", ""Es"": ""Venezuela (República Bolivariana de)"", ""Fr"": ""Venezuela (République bolivarienne du)"", ""Ru"": ""Венесуэла (Боливарианская Республика)""}', 19),
        ('AI', '{""Ar"": ""أنغويلا"", ""Cn"": ""安圭拉"", ""En"": ""Anguilla"", ""Es"": ""Anguila"", ""Fr"": ""Anguilla"", ""Ru"": ""Ангилья""}', 19),
        ('AR', '{""Ar"": ""الأرجنتين"", ""Cn"": ""阿根廷"", ""En"": ""Argentina"", ""Es"": ""Argentina"", ""Fr"": ""Argentine"", ""Ru"": ""Аргентина""}', 19),
        ('AW', '{""Ar"": ""أروبا"", ""Cn"": ""阿鲁巴"", ""En"": ""Aruba"", ""Es"": ""Aruba"", ""Fr"": ""Aruba"", ""Ru"": ""Аруба""}', 19),
        ('BM', '{""Ar"": ""برمودا"", ""Cn"": ""百慕大"", ""En"": ""Bermuda"", ""Es"": ""Bermuda"", ""Fr"": ""Bermudes"", ""Ru"": ""Бермудские острова""}', 19),
        ('BQ', '{""Ar"": ""بونير وسانت يوستاشيوس وسابا"", ""Cn"": ""博纳尔，圣俄斯塔休斯和萨巴"", ""En"": ""Bonaire, Sint Eustatius and Saba"", ""Es"": ""Bonaire, San Eustaquio y Saba"", ""Fr"": ""Bonaire, Saint-Eustache et Saba"", ""Ru"": ""Бонайре, Синт-Эстатиус и Саба""}', 19),
        ('BR', '{""Ar"": ""البرازيل"", ""Cn"": ""巴西"", ""En"": ""Brazil"", ""Es"": ""Brasil"", ""Fr"": ""Brésil"", ""Ru"": ""Бразилия""}', 19),
        ('BV', '{""Ar"": ""جزيرة بوفيت"", ""Cn"": ""布维岛"", ""En"": ""Bouvet Island"", ""Es"": ""Isla Bouvet"", ""Fr"": ""Île Bouvet"", ""Ru"": ""Остров Буве""}', 19),
        ('CA', '{""Ar"": ""كندا"", ""Cn"": ""加拿大"", ""En"": ""Canada"", ""Es"": ""Canadá"", ""Fr"": ""Canada"", ""Ru"": ""Канада""}', 19),
        ('CK', '{""Ar"": ""جزر كوك"", ""Cn"": ""库克群岛"", ""En"": ""Cook Islands"", ""Es"": ""Islas Cook"", ""Fr"": ""Îles Cook"", ""Ru"": ""Острова Кука""}', 9),
        ('CL', '{""Ar"": ""شيلي"", ""Cn"": ""智利"", ""En"": ""Chile"", ""Es"": ""Chile"", ""Fr"": ""Chili"", ""Ru"": ""Чили""}', 19),
        ('CO', '{""Ar"": ""كولومبيا"", ""Cn"": ""哥伦比亚"", ""En"": ""Colombia"", ""Es"": ""Colombia"", ""Fr"": ""Colombie"", ""Ru"": ""Колумбия""}', 19),
        ('EC', '{""Ar"": ""إكوادور"", ""Cn"": ""厄瓜多尔"", ""En"": ""Ecuador"", ""Es"": ""Ecuador"", ""Fr"": ""Équateur"", ""Ru"": ""Эквадор""}', 19),
        ('FJ', '{""Ar"": ""فيجي"", ""Cn"": ""斐济"", ""En"": ""Fiji"", ""Es"": ""Fiji"", ""Fr"": ""Fidji"", ""Ru"": ""Фиджи""}', 9),
        ('FM', '{""Ar"": ""ميكرونيزيا (ولايات - الموحدة)"", ""Cn"": ""密克罗尼西亚联邦"", ""En"": ""Micronesia (Federated States of)"", ""Es"": ""Micronesia (Estados Federados de)"", ""Fr"": ""Micronésie (États fédérés de)"", ""Ru"": ""Микронезия (Федеративные Штаты)""}', 9),
        ('GL', '{""Ar"": ""غرينلند"", ""Cn"": ""格陵兰"", ""En"": ""Greenland"", ""Es"": ""Groenlandia"", ""Fr"": ""Groenland"", ""Ru"": ""Гренландия""}', 19),
        ('GU', '{""Ar"": ""غوام"", ""Cn"": ""关岛"", ""En"": ""Guam"", ""Es"": ""Guam"", ""Fr"": ""Guam"", ""Ru"": ""Гуам""}', 9),
        ('HM', '{""Ar"": ""جزيرة هيرد وجزر ماكدونالد"", ""Cn"": ""赫德岛和麦克唐纳岛"", ""En"": ""Heard Island and McDonald Islands"", ""Es"": ""Islas Heard y McDonald"", ""Fr"": ""Île Heard-et-Îles MacDonald"", ""Ru"": ""Остров Херд и острова Макдональд""}', 9),
        ('KI', '{""Ar"": ""كيريباس"", ""Cn"": ""基里巴斯"", ""En"": ""Kiribati"", ""Es"": ""Kiribati"", ""Fr"": ""Kiribati"", ""Ru"": ""Кирибати""}', 9),
        ('MH', '{""Ar"": ""جزر مارشال"", ""Cn"": ""马绍尔群岛"", ""En"": ""Marshall Islands"", ""Es"": ""Islas Marshall"", ""Fr"": ""Îles Marshall"", ""Ru"": ""Маршалловы Острова""}', 9),
        ('MP', '{""Ar"": ""جزر ماريانا الشمالية"", ""Cn"": ""北马里亚纳群岛"", ""En"": ""Northern Mariana Islands"", ""Es"": ""Islas Marianas Septentrionales"", ""Fr"": ""Îles Mariannes du Nord"", ""Ru"": ""Северные Марианские острова""}', 9),
        ('NC', '{""Ar"": ""كاليدونيا الجديدة"", ""Cn"": ""新喀里多尼亚"", ""En"": ""New Caledonia"", ""Es"": ""Nueva Caledonia"", ""Fr"": ""Nouvelle-Calédonie"", ""Ru"": ""Новая Каледония""}', 9),
        ('NF', '{""Ar"": ""جزيرة نورفولك"", ""Cn"": ""诺福克岛"", ""En"": ""Norfolk Island"", ""Es"": ""Isla Norfolk"", ""Fr"": ""Île Norfolk"", ""Ru"": ""Остров Норфолк""}', 9),
        ('NR', '{""Ar"": ""ناورو"", ""Cn"": ""瑙鲁"", ""En"": ""Nauru"", ""Es"": ""Nauru"", ""Fr"": ""Nauru"", ""Ru"": ""Науру""}', 9),
        ('NU', '{""Ar"": ""نيوي"", ""Cn"": ""纽埃"", ""En"": ""Niue"", ""Es"": ""Niue"", ""Fr"": ""Nioué"", ""Ru"": ""Ниуэ""}', 9),
        ('NZ', '{""Ar"": ""نيوزيلندا"", ""Cn"": ""新西兰"", ""En"": ""New Zealand"", ""Es"": ""Nueva Zelandia"", ""Fr"": ""Nouvelle-Zélande"", ""Ru"": ""Новая Зеландия""}', 9),
        ('PF', '{""Ar"": ""بولينيزيا الفرنسية"", ""Cn"": ""法属波利尼西亚"", ""En"": ""French Polynesia"", ""Es"": ""Polinesia Francesa"", ""Fr"": ""Polynésie française"", ""Ru"": ""Французская Полинезия""}', 9),
        ('PG', '{""Ar"": ""بابوا غينيا الجديدة"", ""Cn"": ""巴布亚新几内亚"", ""En"": ""Papua New Guinea"", ""Es"": ""Papua Nueva Guinea"", ""Fr"": ""Papouasie-Nouvelle-Guinée"", ""Ru"": ""Папуа-Новая Гвинея""}', 9),
        ('PM', '{""Ar"": ""سان بيير وميكلون"", ""Cn"": ""圣皮埃尔和密克隆"", ""En"": ""Saint Pierre and Miquelon"", ""Es"": ""San Pedro y Miquelón"", ""Fr"": ""Saint-Pierre-et-Miquelon"", ""Ru"": ""Сен-Пьер и Микелон""}', 19),
        ('PN', '{""Ar"": ""بيتكرن"", ""Cn"": ""皮特凯恩"", ""En"": ""Pitcairn"", ""Es"": ""Pitcairn"", ""Fr"": ""Pitcairn"", ""Ru"": ""Питкэрн""}', 9),
        ('PW', '{""Ar"": ""بالاو"", ""Cn"": ""帕劳"", ""En"": ""Palau"", ""Es"": ""Palau"", ""Fr"": ""Palaos"", ""Ru"": ""Палау""}', 9),
        ('SB', '{""Ar"": ""جزر سليمان"", ""Cn"": ""所罗门群岛"", ""En"": ""Solomon Islands"", ""Es"": ""Islas Salomón"", ""Fr"": ""Îles Salomon"", ""Ru"": ""Соломоновы Острова""}', 9),
        ('TO', '{""Ar"": ""تونغا"", ""Cn"": ""汤加"", ""En"": ""Tonga"", ""Es"": ""Tonga"", ""Fr"": ""Tonga"", ""Ru"": ""Тонга""}', 9),
        ('TV', '{""Ar"": ""توفالو"", ""Cn"": ""图瓦卢"", ""En"": ""Tuvalu"", ""Es"": ""Tuvalu"", ""Fr"": ""Tuvalu"", ""Ru"": ""Тувалу""}', 9),
        ('US', '{""Ar"": ""الولايات المتحدة الأمريكية"", ""Cn"": ""美利坚合众国"", ""En"": ""United States of America"", ""Es"": ""Estados Unidos de América"", ""Fr"": ""États-Unis d’Amérique"", ""Ru"": ""Соединенные Штаты Америки""}', 19),
        ('VU', '{""Ar"": ""فانواتو"", ""Cn"": ""瓦努阿图"", ""En"": ""Vanuatu"", ""Es"": ""Vanuatu"", ""Fr"": ""Vanuatu"", ""Ru"": ""Вануату""}', 9),
        ('WF', '{""Ar"": ""جزر واليس وفوتونا"", ""Cn"": ""瓦利斯群岛和富图纳群岛"", ""En"": ""Wallis and Futuna Islands"", ""Es"": ""Islas Wallis y Futuna"", ""Fr"": ""Îles Wallis-et-Futuna"", ""Ru"": ""Острова Уоллис и Футуна""}', 9),
        ('WS', '{""Ar"": ""ساموا"", ""Cn"": ""萨摩亚"", ""En"": ""Samoa"", ""Es"": ""Samoa"", ""Fr"": ""Samoa"", ""Ru"": ""Самоа""}', 9),
        ('–', '{""Ar"": ""سارك"", ""Cn"": ""萨克"", ""En"": ""Sark"", ""Es"": ""Sark"", ""Fr"": ""Sercq"", ""Ru"": ""Сарк""}', 150),
        ('AE', '{""Ar"": ""الإمارات العربية المتحدة"", ""Cn"": ""阿拉伯联合酋长国"", ""En"": ""United Arab Emirates"", ""Es"": ""Emiratos Árabes Unidos"", ""Fr"": ""Émirats arabes unis"", ""Ru"": ""Объединенные Арабские Эмираты""}', 142),
        ('AG', '{""Ar"": ""أنتيغوا وبربودا"", ""Cn"": ""安提瓜和巴布达"", ""En"": ""Antigua and Barbuda"", ""Es"": ""Antigua y Barbuda"", ""Fr"": ""Antigua-et-Barbuda"", ""Ru"": ""Антигуа и Барбуда""}', 19),
        ('AL', '{""Ar"": ""ألبانيا"", ""Cn"": ""阿尔巴尼亚"", ""En"": ""Albania"", ""Es"": ""Albania"", ""Fr"": ""Albanie"", ""Ru"": ""Албания""}', 150),
        ('AM', '{""Ar"": ""أرمينيا"", ""Cn"": ""亚美尼亚"", ""En"": ""Armenia"", ""Es"": ""Armenia"", ""Fr"": ""Arménie"", ""Ru"": ""Армения""}', 142),
        ('AO', '{""Ar"": ""أنغولا"", ""Cn"": ""安哥拉"", ""En"": ""Angola"", ""Es"": ""Angola"", ""Fr"": ""Angola"", ""Ru"": ""Ангола""}', 2),
        ('BB', '{""Ar"": ""بربادوس"", ""Cn"": ""巴巴多斯"", ""En"": ""Barbados"", ""Es"": ""Barbados"", ""Fr"": ""Barbade"", ""Ru"": ""Барбадос""}', 19),
        ('BO', '{""Ar"": ""بوليفيا (دولة - المتعددة القوميات)"", ""Cn"": ""多民族玻利维亚国"", ""En"": ""Bolivia (Plurinational State of)"", ""Es"": ""Bolivia (Estado Plurinacional de)"", ""Fr"": ""Bolivie (État plurinational de)"", ""Ru"": ""Боливия (Многонациональное Государство)""}', 19),
        ('CC', '{""Ar"": ""جزر كوكس (كيلينغ)"", ""Cn"": ""科科斯（基林）群岛"", ""En"": ""Cocos (Keeling) Islands"", ""Es"": ""Islas Cocos (Keeling)"", ""Fr"": ""Îles des Cocos (Keeling)"", ""Ru"": ""Кокосовых (Килинг) островов""}', 9),
        ('CD', '{""Ar"": ""جمهورية الكونغو الديمقراطية"", ""Cn"": ""刚果民主共和国"", ""En"": ""Democratic Republic of the Congo"", ""Es"": ""República Democrática del Congo"", ""Fr"": ""République démocratique du Congo"", ""Ru"": ""Демократическая Республика Конго""}', 2),
        ('FI', '{""Ar"": ""فنلندا"", ""Cn"": ""芬兰"", ""En"": ""Finland"", ""Es"": ""Finlandia"", ""Fr"": ""Finlande"", ""Ru"": ""Финляндия""}', 150),
        ('GB', '{""Ar"": ""المملكة المتحدة لبريطانيا العظمى وآيرلندا الشمالية"", ""Cn"": ""大不列颠及北爱尔兰联合王国"", ""En"": ""United Kingdom of Great Britain and Northern Ireland"", ""Es"": ""Reino Unido de Gran Bretaña e Irlanda del Norte"", ""Fr"": ""Royaume-Uni de Grande-Bretagne et d’Irlande du Nord"", ""Ru"": ""Соединенное Королевство Великобритании и Северной Ирландии""}', 150),
        ('IR', '{""Ar"": ""إيران (جمهورية - الإسلامية)"", ""Cn"": ""伊朗伊斯兰共和国"", ""En"": ""Iran (Islamic Republic of)"", ""Es"": ""Irán (República Islámica del)"", ""Fr"": ""Iran (République islamique d’)"", ""Ru"": ""Иран (Исламская Республика)""}', 142),
        ('MD', '{""Ar"": ""جمهورية مولدوفا"", ""Cn"": ""摩尔多瓦共和国"", ""En"": ""Republic of Moldova"", ""Es"": ""República de Moldova"", ""Fr"": ""République de Moldova"", ""Ru"": ""Республика Молдова""}', 150),
        ('TK', '{""Ar"": ""توكيلاو"", ""Cn"": ""托克劳"", ""En"": ""Tokelau"", ""Es"": ""Tokelau"", ""Fr"": ""Tokélaou"", ""Ru"": ""Токелау""}', 9),
        ('UM', '{""Ar"": ""نائية التابعة للولايات المتحدة"", ""Cn"": ""美国本土外小岛屿"", ""En"": ""United States Minor Outlying Islands"", ""Es"": ""Islas menores alejadas de Estados Unidos"", ""Fr"": ""Îles mineures éloignées des États-Unis"", ""Ru"": ""Внешние малые острова Соединенных Штатов""}', 9)
         on conflict (""Code"") DO UPDATE
        SET (""RegionId"", ""Name"") = (excluded.""RegionId"", excluded.""Name"");";
            migrationBuilder.Sql(sqlCountries); 
        
            var sqlLocalities = @"insert into public.""Localities"" (""CountryCode"", ""Name"") VALUES 
                            ('AE', '{""Ar"": ""دبيّ"", ""Cn"": ""阿富汗"", ""En"": ""DUBAI"", ""Es"": ""DUBAI"", ""Fr"": ""DUBAI"", ""Ru"": ""ДУБАЙ""}')";
                        migrationBuilder.Sql(sqlLocalities);

            var sqlBoardBasis = @"INSERT INTO ""public"".""BoardBasis"" (""Code"", ""Name"") 
                                VALUES 
                                ('RO', '{""En"": ""Room Only""}'), 
                                ('SC', '{""En"": ""Self Catering""}'),
                                ('BB', '{""En"": ""Bed and Breakfast""}'),
                                ('HB', '{""En"": ""Half Board""}'),
                                ('FB', '{""En"": ""Full Board""}'),
                                ('AI', '{""En"": ""All Inclusive""}')
                                 ON CONFLICT (""Code"") DO UPDATE 
                                SET ""Name"" = excluded.""Name"";";
             migrationBuilder.Sql(sqlBoardBasis);

        }

    }

}
