START TRANSACTION;

ALTER TABLE "Accommodations" DROP CONSTRAINT "FK_Accommodations_Managers_ManagerId";

ALTER TABLE "BookingOrders" DROP CONSTRAINT "FK_BookingOrders_Managers_ManagerId";

ALTER TABLE "Contracts" DROP CONSTRAINT "FK_Contracts_Managers_ManagerId";

ALTER TABLE "Documents" DROP CONSTRAINT "FK_Documents_Managers_ManagerId";

ALTER TABLE "Images" DROP CONSTRAINT "FK_Images_Managers_ManagerId";

ALTER TABLE "Images" RENAME COLUMN "ManagerId" TO "CompanyId";

ALTER INDEX "IX_Images_ManagerId" RENAME TO "IX_Images_CompanyId";

ALTER TABLE "Documents" RENAME COLUMN "ManagerId" TO "CompanyId";

ALTER INDEX "IX_Documents_ManagerId" RENAME TO "IX_Documents_CompanyId";

ALTER TABLE "Contracts" RENAME COLUMN "ManagerId" TO "CompanyId";

ALTER INDEX "IX_Contracts_ManagerId" RENAME TO "IX_Contracts_CompanyId";

ALTER TABLE "BookingOrders" RENAME COLUMN "ManagerId" TO "CompanyId";

ALTER INDEX "IX_BookingOrders_ManagerId" RENAME TO "IX_BookingOrders_CompanyId";

ALTER TABLE "Accommodations" RENAME COLUMN "ManagerId" TO "CompanyId";

ALTER INDEX "IX_Accommodations_ManagerId" RENAME TO "IX_Accommodations_CompanyId";

ALTER TABLE "Managers" ADD "CompanyId" integer NOT NULL DEFAULT 0;

CREATE TABLE "Companies" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Address" text NOT NULL,
    "PostalCode" text NOT NULL,
    "Phone" text NOT NULL,
    "Website" text NOT NULL,
    "Created" timestamp without time zone NOT NULL,
    "Modified" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Companies" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Managers_CompanyId" ON "Managers" ("CompanyId");


INSERT INTO "Companies" ("Name", "Address", "PostalCode", "Phone", "Website", "Created", "Modified")
VALUES ('First company', '', '', '', '', now(), now());

UPDATE "Accommodations" SET "CompanyId" = 1;

UPDATE "BookingOrders" SET "CompanyId" = 1;

UPDATE "Contracts" SET "CompanyId" = 1;

UPDATE "Documents" SET "CompanyId" = 1;

UPDATE "Images" SET "CompanyId" = 1;

UPDATE "Managers" SET "CompanyId" = 1;


ALTER TABLE "Accommodations" ADD CONSTRAINT "FK_Accommodations_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE SET NULL;

ALTER TABLE "BookingOrders" ADD CONSTRAINT "FK_BookingOrders_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE SET NULL;

ALTER TABLE "Contracts" ADD CONSTRAINT "FK_Contracts_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE SET NULL;

ALTER TABLE "Documents" ADD CONSTRAINT "FK_Documents_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE SET NULL;

ALTER TABLE "Images" ADD CONSTRAINT "FK_Images_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE SET NULL;

ALTER TABLE "Managers" ADD CONSTRAINT "FK_Managers_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201130123039_AddTableCompanies', '5.0.0');

COMMIT;